/*
 * Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekBay.
 *
 * MekBay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekBay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MegaMek was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */

export const MIDDLE_WORD_CORPORATE: string[] = [
    'Advisory',
    'Aegis',
    'Allegiance',
    'Apex',
    'Ascendant',
    'Atlas',
    'Axis',
    'Beacon',
    'Capital',
    'Catalyst',
    'Cipher',
    'Citadel',
    'Command',
    'Concord',
    'Conquest',
    'Consulting',
    'Continuum',
    'Core',
    'Crest',
    'Crucible',
    'Development',
    'Dominion',
    'Dynamics',
    'Dynamo',
    'Element',
    'Elite',
    'Empire',
    'Endeavor',
    'Engineering',
    'Enigma',
    'Enterprise',
    'Envision',
    'Epoch',
    'Excelsior',
    'Exemplar',
    'Fortress',
    'Frontier',
    'Fulcrum',
    'Fusion',
    'Genesis',
    'Gravitas',
    'Grit',
    'Helix',
    'Holdings',
    'Horizon',
    'Ignite',
    'Impact',
    'Imperium',
    'Impetus',
    'Inception',
    'Innovations',
    'Insight',
    'Integration',
    'Integrity',
    'Intrepid',
    'Investments',
    'Invictus',
    'Kinetics',
    'Legacy',
    'Liberty',
    'Logistics',
    'Lumina',
    'Luminary',
    'Management',
    'Matrix',
    'Meridian',
    'Modus',
    'Momentum',
    'Monument',
    'Nebula',
    'Networks',
    'Nexus',
    'Nova',
    'Objective',
    'Obsidian',
    'Onyx',
    'Operations',
    'Optima',
    'Optimum',
    'Origin',
    'Paradigm',
    'Paragon',
    'Partners',
    'Pinnacle',
    'Pioneer',
    'Praxis',
    'Precision',
    'Prestige',
    'Prime',
    'Prism',
    'Prodigy',
    'Prospect',
    'Pulse',
    'Quantum',
    'Radiance',
    'Raptor',
    'Realm',
    'Reign',
    'Repute',
    'Resolute',
    'Resolve',
    'Resources',
    'Revive',
    'Rising',
    'Savant',
    'Sentinel',
    'Services',
    'Solstice',
    'Solutions',
    'Sovereign',
    'Spectrum',
    'Strategies',
    'Strategy',
    'Stratos',
    'Summit',
    'Surge',
    'Synergy',
    'Systems',
    'Technologies',
    'Tenacity',
    'Titan',
    'Torque',
    'Traverse',
    'Trident',
    'Triumph',
    'Unity',
    'Valor',
    'Vanguard',
    'Vector',
    'Velocity',
    'Venture',
    'Veritas',
    'Vertex',
    'Vision',
    'Vortex',
    'Zenith',
    'Zephyr'
];

export const END_WORD_CORPORATE: string[] = [
    'Advisory',
    'Alliance',
    'Associates',
    'Capital',
    'Consortium',
    'Consulting',
    'Corporation',
    'Development',
    'Dynamics',
    'Engineering',
    'Enterprises',
    'Global',
    'Group',
    'Holdings',
    'Infrastructure',
    'Innovations',
    'Integration',
    'Investments',
    'Logistics',
    'Management',
    'Networks',
    'Operations',
    'Partners',
    'Resources',
    'Services',
    'Solutions',
    'Strategies',
    'Systems',
    'Technologies',
    'Ventures'
];

export const MIDDLE_WORD_MERCENARY: string[] = [
    'Aegis',
    'Anvil',
    'Apex',
    'Arcane',
    'Ashen',
    'Atlas',
    'Avenger',
    'Bastion',
    'Blackhawk',
    'Blackout',
    'Blade',
    'Blaze',
    'Blitz',
    'Bloodhound',
    'Brawler',
    'Brimstone',
    'Cinder',
    'Cobalt',
    'Cobra',
    'Colossus',
    'Comet',
    'Crusader',
    'Cyclone',
    'Darkhawk',
    'Direwolf',
    'Draconis',
    'Drakon',
    'Dread',
    'Dreadnought',
    'Drifter',
    'Echelon',
    'Eclipse',
    'Ember',
    'Enforcer',
    'Enigma',
    'Falcon',
    'Falconer',
    'Feral',
    'Forge',
    'Frost',
    'Frostbite',
    'Fury',
    'Ghost',
    'Gladiator',
    'Gladius',
    'Grim',
    'Guardian',
    'Hammer',
    'Harbinger',
    'Harrier',
    'Havoc',
    'Helix',
    'Hellfire',
    'Hellhound',
    'Hunter',
    'Inferno',
    'Iron',
    'Ironclad',
    'Ironfist',
    'Ironheart',
    'Ironhide',
    'Javelin',
    'Juggernaut',
    'Knight',
    'Lynx',
    'Maelstrom',
    'Marauding',
    'Mercenary',
    'Mirage',
    'Nightfall',
    'Nightshade',
    'Nomad',
    'Nova',
    'Obsidian',
    'Omen',
    'Onyx',
    'Orion',
    'Outlaw',
    'Outrider',
    'Panther',
    'Phalanx',
    'Phantom',
    'Phoenix',
    'Predator',
    'Pyre',
    'Pyro',
    'Quasar',
    'Rampage',
    'Rampart',
    'Ranger',
    'Raptor',
    'Ravager',
    'Raven',
    'Ravenous',
    'Razor',
    'Reaper',
    'Reaver',
    'Rebellion',
    'Reckoning',
    'Reign',
    'Renegade',
    'Rogue',
    'Sabre',
    'Scorpion',
    'Scourge',
    'Sentinel',
    'Shadow',
    'Shadowhawk',
    'Shard',
    'Shatter',
    'Shrapnel',
    'Skyhawk',
    'Specter',
    'Spectral',
    'Spectre',
    'Starfire',
    'Steel',
    'Storm',
    'Stormbreaker',
    'Stormbringer',
    'Stormwatch',
    'Stratos',
    'Strider',
    'Strike',
    'Striker',
    'Surge',
    'Talon',
    'Tempest',
    'Thunder',
    'Thunderbolt',
    'Thunderstorm',
    'Thunderstrike',
    'Titan',
    'Titanfall',
    'Titanis',
    'Tracer',
    'Valkyrie',
    'Valor',
    'Vanguard',
    'Venom',
    'Vindicator',
    'Viper',
    'Vortex',
    'Vulcan',
    'Warhound',
    'Warlock',
    'Warlord',
    'Warpath',
    'Wolf',
    'Wolfpack',
    'Wraith',
    'Wrath',
    'Zenith',
    'Zephyr'
];

export const END_WORD_MERCENARY: string[] = [
    'Adversaries',
    'Aegis',
    'Assassins',
    'Assault',
    'Avatars',
    'Avengers',
    'Banshees',
    'Battalions',
    'Battlemages',
    'Berserkers',
    'Blackguards',
    'Blackhawks',
    'Blacksmiths',
    'Blades',
    'Bladesmen',
    'Blitzers',
    'Bounty Hunters',
    'Brigade',
    'Brigands',
    'Bulwarks',
    'Cataphracts',
    'Carabiniers',
    'Cossacks',
    'Cavaliers',
    'Cavalry',
    'Centurions',
    'Commanders',
    'Chevau-légers',
    'Chasseurs',
    'Commandos',
    'Conquerors',
    'Cuirassiers',
    'Corsairs',
    'Crusaders',
    'Defenders',
    'Defiance',
    'Dogs',
    'Dominators',
    'Dominion',
    'Dragons',
    'Dragonslayers',
    'Dragoons',
    'Dreadlords',
    'Dreadnaughts',
    'Druids',
    'Elites',
    'Enforcers',
    'Enigma',
    'Exiles',
    'Falcons',
    'Firebrands',
    'Frontiers',
    'Frontliner',
    'Frostborn',
    'Furies',
    'Fury',
    'Fusiliers',
    'Ghosts',
    'Golems',
    'Goliaths',
    'Grimhearts',
    'Grenadiers',
    'Gryphons',
    'Guardians',
    'Gunners',
    'Gunslingers',
    'Harbingers',
    'Hawkmen',
    'Hawks',
    'Hellhounds',
    'Hellions',
    'Hounds',
    'Hunters',
    'Huntsmen',
    'Huskies',
    'Infiltrators',
    'Invaders',
    'Invictus',
    'Ironclads',
    'Ironmen',
    'Janissaries',
    'Juggernauts',
    'Jägers',
    'Knights',
    'Lancers',
    'Landsknechte',
    'Legends',
    'Legion',
    'Legionnaires',
    'Light Horse',
    'Lynx',
    'Maelstrom',
    'Mamluks',
    'Marauders',
    'Maulers',
    'Mavericks',
    'Mercenaries',
    'Mercs',
    'Nomads',
    'Outcasts',
    'Outlaws',
    'Outriders',
    'Pathfinders',
    'Phalanx',
    'Phantom',
    'Phantoms',
    'Pillars',
    'Pioneers',
    'Predators',
    'Prowlers',
    'Raiders',
    'Rangers',
    'Raptors',
    'Ravagers',
    'Reapers',
    'Reavers',
    'Rebels',
    'Recon',
    'Recruits',
    'Renegades',
    'Reiters',
    'Resolutes',
    'Riders',
    'Riflemen',
    'Riptides',
    'Rivals',
    'Rogues',
    'Runners',
    'Sabers',
    'Saboteurs',
    'Savages',
    'Scorpions',
    'Scouts',
    'Seekers',
    'Seers',
    'Sentinels',
    'Sentries',
    'Shadowhunters',
    'Shadowlords',
    'Shadowmen',
    'Shadows',
    'Sharpshooters',
    'Shockers',
    'Shocktroopers',
    'Shocktroops',
    'Shockwave',
    'Sipahis',
    'Skirmishers',
    'Skyfighters',
    'Skyhawks',
    'Skywalkers',
    'Slayers',
    'Sovereigns',
    'Spartans',
    'Specters',
    'Stalkers',
    'Stormborn',
    'Stormbreakers',
    'Stormbringers',
    'Stormguard',
    'Stormlords',
    'Stormriders',
    'Stormrunners',
    'Striders',
    'Strikers',
    'Syndicate',
    'Tactical',
    'Tacticians',
    'Tempests',
    'Terrors',
    'Thunderbolts',
    'Thunderers',
    'Tigers',
    'Titans',
    'Tracers',
    'Tridents',
    'Troubleshooters',
    'Uhlans',
    'Vanguard',
    'Vanquishers',
    'Vigilantes',
    'Vikings',
    'Vortex',
    'Voltigeurs',
    'Warband',
    'Warbringers',
    'Wardens',
    'Warhounds',
    'Warlocks',
    'Warlords',
    'Warriors',
    'Watchdogs',
    'Watchers',
    'Wolfpack',
    'Wolves',
    'Wraiths'
];

export const PRE_FAB: string[] = [
    'Accidentally Awesome',
    'Adrenaline Accidentals',
    'Adrenaline Junkies',
    'Against the Butt',
    'Aimless Artillery',
    'Apocalypse Maybes',
    'Armchair Admirals',
    'Armor Amateurs',
    'Armor Anomalies',
    'Armor in Progress',
    'Armor-Piercing Amateurs',
    'Armored Amateurs',
    'Armored Antics',
    'Armored by Duct Tape',
    'Arrow IV Assistants',
    'Ash and Cinders',
    'Assembled on Arrival',
    'Backfire Battalion',
    'Backfire Brothers',
    'Backup Bandits',
    'Backup Blunderers',
    'Backup Breakers',
    'Band-Aid Brigade',
    'Bandaged Battalion',
    'Bang and Clang Brigade',
    'Bar Tab Heroes',
    'Battered and Bruised',
    'Battered Bandits',
    'Battle-Damaged Besties',
    'Battle-Fatigued Bandits',
    'Battle-Scarred Buccaneers',
    'Battle-Stained Blunderers',
    'Battlehardened Baffoons',
    'Bent Antenna Brigade',
    'Bent Barrel Blasters',
    'Bent Blades',
    'Bent Chassis Battalion',
    'Bent Frame Fighters',
    'Big Red Button Bashers',
    'Black Box Reliables',
    'Blackout Battalion',
    'Blast Radius Battalion',
    'Blazing Disasters',
    'Blind Luck Battalion',
    'Blindside Battalion',
    'Blips on the Radar',
    'Blitz and Bash Brigade',
    'Blitz and Bungle Buddies',
    'Blitz and Glitz',
    'Blitzed Brawlers',
    'Blown Fuses',
    'Blown-Out Battalion',
    'Blue-Screen Battalion',
    'Blunder Brigade',
    'Blunderbuss Battalion',
    'Blundered Battalion',
    'Blunders & Ballistics',
    'Blunders and Brawn',
    'Bodge Job Buggers',
    'Bolt Loosened Legion',
    'Bolted Together',
    'Bonked Battalion',
    'Boom or Bust Brigade',
    'Bootleg Brigade',
    'Bootstrapped Battalion',
    'Botched Effort',
    'Brainfart Brigade',
    'Brake Failure Battalion',
    'Breakdown Brigade',
    'Brick Wall Battalion',
    'Broken Barrel Bandits',
    'Broken Battlebots',
    'Broken Bits',
    'Broken Compass Crew',
    'Broken Gear Gang',
    'Broken-Bolt Battalion',
    'Broken-Down Battlers',
    'Budget Brawlers',
    'Bumbling Bombardiers',
    'Bumpy Battalion',
    'Burn Barrel Battalion',
    'Burnout Brothers',
    'Burnt Circuit Battalion',
    'Burnt Offerings',
    'Burnt Out Brawlers',
    'Bust-Up Battalion',
    'Busted Bearings',
    'Busted Blades',
    'Busted Bolts Brigade',
    'Button Mashing Maniacs',
    'Button Pushers',
    'Button Smashers',
    'Buyer Regrets',
    'Buzzed Blasters',
    'By the Seat of Our Pants',
    'Calamity Corps',
    'Call for Backup',
    'Cannon Fodder Cartel',
    'Casual Casualties',
    'Casualty Collectors',
    'Catapulted Chaos',
    'Catastrophic Crusaders',
    'Caution Tape Corps',
    'Chaos Consultants',
    'Chipped Armor Crew',
    'Circuit Snaggers',
    'Circuit-Breaker Commandos',
    'Circuitbreakers',
    'Clogged Cannons',
    'Close Enough Corps',
    'Clueless Commandos',
    'Cluster Cannon Crew',
    'Clusterstrike Crew',
    'Cobweb Commanders',
    'Code Red Rejects',
    'Coffee and Chaos',
    'Coin Toss Corps',
    'Collateral Cowboys',
    'Collateral Damage Experts',
    'Collision Course Corps',
    'Comically Underprepared',
    'Conscripted Chaos',
    'Contractual Obligations',
    'Cracked Cannoneers',
    'Cracked Casings',
    'Cracked Circuitry Crew',
    'Cracked Combatants',
    'Cracked Core',
    'Cracked Crew',
    'Cracked Shell Crew',
    'Crash and Burn Bumblers',
    'Crash Land Crusaders',
    'Crash Test Commandos',
    'Creaky Commandos',
    'Creaky Crushers',
    'Crooked Cannons',
    'Cross-Eyed Commandos',
    'Crossfire Cavaliers',
    'Crossfire Crew',
    'Crosshair Conundrum',
    'Crosswired Commanders',
    'Crumbling Command',
    'Cursed Contracts',
    'Damaged Defenders',
    'Dead Batteries Battalion',
    'Death by Committee',
    'Defective Division',
    'Defunct Defenders',
    'Delayed Deployments',
    'Delayed Reaction Division',
    'Dented Dominators',
    'Derailed Defenders',
    'Derailed Division',
    'Derailment Division',
    'Derelict Division',
    'Desperate Measures',
    'Detour Division',
    'Dimwit Division',
    'Disarray Division',
    'Disasterpiece',
    'Discombobulated Buddies',
    'Disconnected Disasters',
    'Discount Death Dealers',
    'Disheveled Defenders',
    'Disordered Defenders',
    'Disorganized Desperados',
    'Disrupted Defenders',
    'Diverted Division',
    'DIY Doomsday',
    'Doom Delivery',
    'Doomsday Dilettantes',
    'Double-Booked',
    'Downrange Desperados',
    'Downtime Defenders',
    'Drain Plug Defenders',
    'Drop Zone Debacle',
    'Drop Zone Disasters',
    'Drop-in Drifters',
    'Drunken Drop Troops',
    'Duct-Tape Dynamos',
    'Duct-Taped Defenders',
    'Dumb Luck Defense',
    'Dust Bunnies Division',
    'Dusty Pilots',
    'Ejector Seat Squadron',
    'Emergency Backup Battalion',
    'Emergency Contractors',
    'Emergency Escapes',
    'Emergency Excavators',
    'Emergency Rations',
    'Engine Failure Fugitives',
    'Engineered Explosions',
    'Error 404',
    'Error Code Commanders',
    'Expendable Elites',
    'Expired Licenses',
    'Explosive Expectations',
    'Explosive Expendables',
    'Explosive Solutions',
    'Failed Launch',
    'Fallout Fighters',
    'False Alarms',
    'Faulty Firepower',
    'Faulty Force',
    'Faulty Frontliners',
    'Faulty Fusiliers',
    'Fidgety Fighters',
    'Final Frontier Fools',
    'Final Fumble',
    'Final Standers',
    'Fire and Forget',
    'Fire Hazard Forces',
    'Fire Sale Fighters',
    'Fired Up Fighters',
    'Firepower Flops',
    'Firepower Flunkies',
    'Firestorm Freelancers',
    'Fizzle Force',
    'Fizzled Flames',
    'Fizzled Force',
    'Fizzled Fusiliers',
    'Flak Jacket Jesters',
    'Flammable Forces',
    'Flare-Up Fighters',
    'Flash-Fried Fighters',
    'Flat Tire Fighters',
    'Flatline Fumblers',
    'Flawed Firepower',
    'Flickering Fireteam',
    'Flimsy Fusiliers',
    'Flipped Switch Squadron',
    'Fluke Fighters',
    'Fly-By-Night',
    'Flying Fiasco',
    'Flywheel Fighters',
    'Fools for Hire',
    'For Sale Battalion',
    'Forgetful Forces',
    'Forgotten Firepower',
    'Fractured Fighters',
    'Fractured Fireteam',
    'Frag and Forget',
    'Frag Fest Fighters',
    'Fragged and Forgotten',
    'Fragged Fighters',
    'Fragile Fighters',
    'Fragmented Forces',
    'FrankenMeks',
    'Frayed Forces',
    'Frazzled Fusiliers',
    'Freeloading Fighters',
    'Frenzied Freelancers',
    'Frenzy Fighters',
    'Freshly Repaired',
    'Friendly Fire Squad',
    'Friendly Firefighters',
    'Frying Pan Fighters',
    'Fuel Tank Fumblers',
    'Full Metal Farce',
    'Full Tilt Troopers',
    'Full-Throttle Failures',
    'Fumble and Fire',
    'Fumble Force',
    'Fumbling Phantoms',
    'Funky Firepower',
    'Fuse Blown Battalion',
    'Fuse-Breakers',
    'Gas-Guzzling Giants',
    'Gear Grind Guardians',
    'Gear Slip Squad',
    'Gears and Gremlins',
    'Gearshift Goons',
    'Ghost Grenadiers',
    'Glitch and Grind',
    'Glitch Gang',
    'Glitch Gunners',
    'Glitch in the System',
    'Glitch-Gear Gang',
    'Glitched Gears',
    'Glitched Gladiators',
    'Glitchy Gizmos',
    'Glitchy Grunts',
    'Glorious Goofballs',
    'Glorious Misfires',
    'Golden BBs',
    'Gravy Train Gunners',
    'Greased Lightning Legion',
    'Greasy Gearheads',
    'Gridlock Gladiators',
    'Half-Baked Heroes',
    'Half-Cocked Hotshots',
    'Half-Mek Hellraisers',
    'Half-Pint Heroes',
    'Half-Power Heroes',
    'Half-Step Heroes',
    'Halfway Heroes',
    'Hand-Me-Down Heroes',
    'Happy Accidents',
    'Hasty Hires',
    'Haywire Havoc',
    'Hazardous Hardware',
    'Hazardous Heroes',
    'Hazardous Hijinks',
    'Hazardous Hitmen',
    'Hazardous Hooligans',
    'Hazardous Hotshots',
    'Help I Can\'t Get Up',
    'Helter Skelter Squad',
    'Hiccups and Hooligans',
    'Hijinks Militia',
    'Hot Drop Heroes',
    'Hot Mess',
    'Hotwired Heroes',
    'Hull Breach Hooligans',
    'Hull Patch Heroes',
    'Hypothetical Heroes',
    'Idle Iron Brigade',
    'Imbalanced Invaders',
    'Improvised Explosions',
    'Improvised Mayhem',
    'In Over Our Heads',
    'Inept Invasion',
    'Inferno Investors',
    'Infinite Ammo',
    'Inside Job',
    'Instant Infantry',
    'Jagged Edge Juggernauts',
    'Jammed Gyros',
    'Jammed Jets',
    'Janky Jokers',
    'Janky Juggernauts',
    'Jettisoned Jokers',
    'Jiggly Juggernauts',
    'Juggled Justice',
    'Junkyard Jockeys',
    'Jury-Rigged Junkies',
    'Jury-Rigged Justice',
    'Kicking and Screaming',
    'Kickstart Commandos',
    'Knockoff Knights',
    'Lagging Legends',
    'Last Chance Corps',
    'Last Ditch Legion',
    'Last Minute Marauders',
    'Last Standers',
    'Last-Minute Reinforcements',
    'Leadfoot Legion',
    'Left-Handed Losers',
    'Legal Liability',
    'Limping Legionnaires',
    'Lock Stock and Misfire',
    'Long Con',
    'Long Haul Legion',
    'Longshot Legends',
    'Look Mom I\'m a Mercenary',
    'Loophole Legion',
    'Loose Bolts',
    'Loose Ends Legion',
    'Loose Screws Legion',
    'Loosely Assembled',
    'Lopsided Legion',
    'Lost Cause Legion',
    'LosTech Losers',
    'Loud and Reckless',
    'Low Ammo Legends',
    'Low Budget Legion',
    'Lucky Strikes',
    'Madcap Militia',
    'Makeshift Marauders',
    'Malfunction Masters',
    'Malfunction Militia',
    'Malfunctioned Militia',
    'Mangled Mercs',
    'Manual Override Militia',
    'Mek Head Mayhem',
    'Mek Messiahs',
    'Mecha Misfits',
    'Mecha-nicians',
    'Mechanical Mishaps',
    'Mediocre Militia',
    'Meltdown Militia',
    'Menace Meks',
    'Metal Mayhem Marauders',
    'Metalhead Malcontents',
    'Midnight Marauders',
    'Misaligned Mercs',
    'Miscalculated Maneuvers',
    'Misfire Marauders',
    'Misfire Masters',
    'Misfire Misfits',
    'Misfired Mercenaries',
    'Misfired Missiles',
    'Misfired Orders',
    'Misfit Maniacs',
    'Misfit Mek Squad',
    'Misguided Missiles',
    'Mishap Militia',
    'Mismatched Mercenaries',
    'Missed Connection Militia',
    'Missile Malcontents',
    'Missing Manuals',
    'Missing Mek Parts',
    'Misstep Mercenaries',
    'Mixed Messages',
    'Moonshine Marauders',
    'More Missiles Misfits',
    'Muddled Mercs',
    'Muddy Boots Brigade',
    'Near Miss Knights',
    'No Armor Ninjas',
    'No Arms No Ammo',
    'No Reserves',
    'No Signal Soldiers',
    'No Spare Parts',
    'No Warranty',
    'No-Load Legion',
    'Not Quite Heroes',
    'Not Ready Yet',
    'Not the Wolf\'s Dragoons',
    'Oddball Ordnance',
    'Off the Rails Regiment',
    'Off-Kilter Killers',
    'Off-Target Team',
    'Off-the-Charts Chaos',
    'Off-Track Tacticians',
    'Offbeat Battalion',
    'Offbeat Outlaws',
    'On Fire and Loving It',
    'On the Fritz',
    'One Hit Wonders',
    'One Speed Spinners',
    'Oops Brigade',
    'Out of Order Operatives',
    'Out-of-Range Rangers',
    'Out-of-Sync Squad',
    'Outdated Operators',
    'Outgunned Outlaws',
    'Overbudget Overlords',
    'Overburdened Battalion',
    'Overclocked Outcasts',
    'Overclocked Underachievers',
    'Overdraft Ordnance',
    'Overdrive Outcasts',
    'Overdue Loans',
    'Overheating Ordnance',
    'Overload Outcasts',
    'Overloaded and Underpaid',
    'Overloaded Oafs',
    'Overpriced Offensive',
    'Overtime Oathbreakers',
    'Overworked Outcasts',
    'Paid in Promises',
    'Panic Button Platoon',
    'Pants-on-Fire',
    'Partial Payments',
    'Parts Unknown',
    'Patch Job Platoon',
    'Patch-Up Patrol',
    'Patched-Up Patriots',
    'Patchwork Paladins',
    'Patchy Pioneers',
    'Patchy Platoon',
    'Phantom Foibles',
    'Pieced Together Platoon',
    'Piecemeal Punishers',
    'Plan B Battalion',
    'Plot Armor',
    'Plug-and-Play Platoon',
    'Plugged-in Patriots',
    'Plummeting Platoon',
    'Pocket Aces',
    'Pocket-Sized Platoon',
    'Pothole Pilots',
    'Power Down Platoon',
    'Power Surge Platoon',
    'Power-Pipe Patrol',
    'Premature Ejectulation',
    'Princess Punching Bags',
    'Prone to Malfunction',
    'Protocol Pirates',
    'Prototype Punishers',
    'Punchline Platoon',
    'Questionable Contracts',
    'Quick Fix Crew',
    'Quirky Quarrelers',
    'Ragged Renegades',
    'Ragtag Raiders',
    'Ragtag Renegades',
    'Ragtag Rogues',
    'Rambling Raiders',
    'Ramshackle Renegades',
    'Random-Retreat Regiment',
    'Rapid Retreat',
    'Rattle-Trap Regiment',
    'Rattled Raiders',
    'Reactor Rejects',
    'Reactor Shield Drifters',
    'Rebooted Rangers',
    'Rebuilt Renegades',
    'Reckless Rookies',
    'Reckless Wagers',
    'Recoil Rogues',
    'Recycled Raiders',
    'Red Alert Rejects',
    'Red Line Raiders',
    'Red-Tape Raiders',
    'Redline Rejects',
    'Reinforced Ramblers',
    'Reinforcements R Us',
    'Rent-a-Reckoning',
    'Rent-a-Riot',
    'Repair Required',
    'Retro Rocket Rangers',
    'Rewired Renegades',
    'Risky Reclaimers',
    'Rocket Rangers',
    'Rogue Riveters',
    'Rolling Blunders',
    'Rolling Thunder',
    'Rolling Wreckers',
    'Rookie Rollcall',
    'Rookie Rollouts',
    'Rough and Rusty',
    'Rough Draft Raiders',
    'Rubber Band Revolution',
    'Rumble in Progress',
    'Rumble Reserves',
    'Runaway Regiment',
    'Runaway Relics',
    'Runaway Rockets',
    'Running Hot',
    'Running on Fumes',
    'Running with Rockets',
    'Rust and Ruin',
    'Rust Belt Renegades',
    'Rust-Ridden Rangers',
    'Rust-Streaked Regulars',
    'Rustbucket Revival',
    'Rusted Recon',
    'Rusted Relics',
    'Rusted Reserves',
    'Rustproof Rebels',
    'Rusty and Ready',
    'Rusty Bolts',
    'Rusty Raiders',
    'Rusty Rebels',
    'Rusty Recon',
    'Rusty Relics',
    'Rusty Rifles',
    'Safety Switch Savages',
    'Salvage Kings',
    'Salvaged Payday',
    'Sandbag Sentries',
    'Sandblasted Sabres',
    'Scatterbrain Squadron',
    'Scattered Shots',
    'Scattershot Squad',
    'Scramble Squadron',
    'Scrap Metal Scoundrels',
    'Scrap Pile Patriots',
    'Scrap-Heap Heroes',
    'Scrapbook Squadron',
    'Scrapbox Strikers',
    'Scraped Together Squad',
    'Scrapheap Heroes',
    'Scrapheap Savants',
    'Scrapheap Squadron',
    'Scrapped Salvagers',
    'Scrapped Scouts',
    'Scrappy Survivors',
    'Scrapyard Soldiers',
    'Scratched Shields',
    'Scuffed Sentries',
    'Seat-of-the-Pants',
    'Seatbelt Checkers',
    'Second-Hand Soldiers',
    'Second String Squadron',
    'Shaky Shots',
    'Shell-Shocked Savages',
    'Shenanigans Squadron',
    'Shiny Objects Brigade',
    'Shiny Screw-ups',
    'Shock Troop Screw-ups',
    'Shocked Squad',
    'Shoddy Squad',
    'Shoot First Syndicate',
    'Shooting Blanks',
    'Short Circuit Savants',
    'Short Fuse Squad',
    'Short-Changed Soldiers',
    'Short-Circuit Squad',
    'Shot in the Dark',
    'Shotgun Riders',
    'Shotgun Shenanigans',
    'Shrapnel Shufflers',
    'Side Hustle Heroes',
    'Side Quest Squad',
    'Sideways Savants',
    'Sidewind Squadron',
    'Sidewinder Squad',
    'Sidewinders and Stumblers',
    'Siege in Progress',
    'Silver-Tongued Saboteurs',
    'Situational Screw-ups',
    'Skeleton Crew',
    'Sketchy Salvagers',
    'Skewed Shots',
    'Skid Row Soldiers',
    'Skidmark Specialists',
    'Slapdash Syndicate',
    'Sledgehammer Savants',
    'Sleep-Deprived Strategists',
    'Slippery Squad',
    'Slipshod Sentries',
    'Slow Motion Mayhem',
    'Slow Start Sabres',
    'Slow-Mo Squad',
    'Smash and Scramble',
    'Smoke and Mirrors',
    'Smoke Bomb Soldiers',
    'Smoke Break Brigade',
    'Smoking Caskets',
    'Snap Crackle and Boom',
    'Space Junk Squad',
    'Spare Bullet Squad',
    'Spare Change Squad',
    'Spare Parts Platoon',
    'Spare Time Soldiers',
    'Spare Tire Syndicate',
    'Speed Bump Soldiers',
    'Speed Bump Soldiers',
    'Sprocket Squad',
    'Spun Out Squadron',
    'Sputtering Sparks',
    'Stackpole Survivors',
    'Stall Tactics',
    'Stalled Strike-Force',
    'Static Shock Troopers',
    'Static Surge Squad',
    'Steam-Powered Saboteurs',
    'Strategic Stumblers',
    'Stray Shells',
    'Stray Shot Specialists',
    'Stray Sparks',
    'Stress-Test Squad',
    'Stressed Out Soldiers',
    'Stressed Systems Squad',
    'Stripped Screw Squadron',
    'Stuck in Neutral',
    'Stuck on Overdrive',
    'Stuck Throttle Squad',
    'Stumble Squad',
    'Stutter Step Squad',
    'Suboptimal Solutions',
    'Sudden Impact',
    'Sudden Scramble',
    'Surrender Pending',
    'Tactical Malfunctions',
    'Tactical Tangles',
    'Tactical Tantrums',
    'Tactical Terrors',
    'Tactical Time-Out',
    'Tactical Turbulence',
    'Tangled Turrets',
    'Tanglefoot Troopers',
    'Tarnished Tacticians',
    'Tattered Titans',
    'Teetering Titans',
    'Tempest Tossed',
    'Temporary Terrors',
    'This Way Up Warriors',
    'Thrift Store Titans',
    'Thrill Seekers',
    'Throttle Stuck',
    'Tick Tock Troopers',
    'Ticklish Titans',
    'Tilted Towers',
    'Time Bomb Team',
    'Tin Can Terrors',
    'Tinfoil Tacticians',
    'Tinkerers of Terror',
    'Too Many Buttons',
    'Trigger Fingers',
    'Trigger Twitch',
    'Trigger-Happy Terrors',
    'Tripped Circuits',
    'Tumbledown Troopers',
    'Tumbleweeds of Terror',
    'Turbo Tap-Out',
    'Turbo Terrorists',
    'Turbo Trouble',
    'Turbo Turtles',
    'Turbocharged Trouble',
    'Turbulent Task Force',
    'Turret Turncoats',
    'Twisted Throttle',
    'Twitching Trigger Fingers',
    'Undercover Underachievers',
    'Underfunded & Overloaded',
    'Underfunded Overlords',
    'Unfortunate Undergraduates',
    'Unhinged Union',
    'Unlikely Alliance',
    'Unpaid Interns',
    'Upgraded Improvisation',
    'Vandalized Vanguards',
    'Vaporwave Vanguard',
    'War Crime Warriors',
    'War Crimes and Misdemeanors',
    'War Junkie Jesters',
    'Warheads Without a Cause',
    'Warpath Wanderers',
    'Warpath Wobblers',
    'Warped Wingnuts',
    'Warzone Wannabes',
    'Wayward Warlords',
    'Wild Card Warriors',
    'Wildcard Warhawks',
    'Winging It Warriors',
    'Wired Wrong',
    'Wobble Wheel Warriors',
    'Wobbling Warheads',
    'Wobbling Warriors',
    'Wobbly War Machines',
    'Worn Out Warriors',
    'Worn Warriors',
    'Worn-War Warriors',
    'Wreckage Walkers',
    'Wrecking Ball Battalion',
    'Wrecking Crew',
    'Wrecks and Ruin',
    'Zapped Zeta Squad'
];

