// Copyright (C) 2026 The MegaMek Team
// SPDX-License-Identifier: GPL-3.0-or-later
// Author: Drake

export type AmmoMunitionFlag =
    | "M_ADA"
    | "M_AIRBURST"
    | "M_ANTI_PERSONNEL"
    | "M_ANTI_TSM"
    | "M_ARAD"
    | "M_ARMOR_PIERCING"
    | "M_ARTEMIS_CAPABLE"
    | "M_ARTEMIS_V_CAPABLE"
    | "M_AX_HEAD"
    | "M_CASELESS"
    | "M_CHAFF"
    | "M_CLUSTER"
    | "M_COOLANT"
    | "M_DAVY_CROCKETT_M"
    | "M_DEAD_FIRE"
    | "M_ECM"
    | "M_EXPLOSIVE"
    | "M_EXTENDED_RANGE"
    | "M_FAE"
    | "M_FASCAM"
    | "M_FLAK"
    | "M_FLARE"
    | "M_FLECHETTE"
    | "M_FOLLOW_THE_LEADER"
    | "M_FRAGMENTATION"
    | "M_HAYWIRE"
    | "M_HEAT_SEEKING"
    | "M_HIGH_EXPLOSIVE"
    | "M_HOMING"
    | "M_IATM_IIW"
    | "M_IATM_IMP"
    | "M_INCENDIARY"
    | "M_INCENDIARY_LRM"
    | "M_INFERNO"
    | "M_INFERNO_IV"
    | "M_LASER_INHIB"
    | "M_LISTEN_KILL"
    | "M_MAGNETIC_PULSE"
    | "M_MINE_CLEARANCE"
    | "M_MULTI_PURPOSE"
    | "M_NARC_CAPABLE"
    | "M_NARC_EX"
    | "M_NEMESIS"
    | "M_PRECISION"
    | "M_SEMIGUIDED"
    | "M_SMOKE"
    | "M_SMOKE_WARHEAD"
    | "M_STANDARD"
    | "M_SWARM"
    | "M_SWARM_I"
    | "M_TANDEM_CHARGE"
    | "M_THUNDER"
    | "M_THUNDER_ACTIVE"
    | "M_THUNDER_AUGMENTED"
    | "M_THUNDER_INFERNO"
    | "M_THUNDER_VIBRABOMB"
    | "M_TORPEDO"
    | "M_TRACER"
    | "M_VIBRABOMB_IV"
;
