
export type RatTier = 'staple' | 'common' | 'present' | 'rare';
export const RAT_TIER_WEIGHT: Record<RatTier, number> = { staple: 8, common: 4, present: 2, rare: 1 };
/** Multiplier applied to the heuristic weight of eligible chassis NOT listed for a matched faction. */
export const UNLISTED_DAMPING = 0.35;

export interface RatWeightTable {
    /** MekBay faction.name matches (canonical first). */
    faction: string[];
    /** Coarse era window (campaign start year). */
    yearFrom: number;
    yearTo: number;
    entries: { chassis: string; tier: RatTier; note?: string }[];
    sources: string[];
}

export const RAT_WEIGHTS: RatWeightTable[] = [
    {
        faction: ['Draconis Combine', 'House Kurita'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'present', note: 'canon 3025: 3% (LCT-1V, LCT-1E)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 2% (STG-3R)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 3% (WSP-1A, WSP-1K); + ~0.24% Special (WSP-1A)' },
            { chassis: 'Spider', tier: 'rare', note: 'canon 3025: 1% (SDR-5K)' },
            { chassis: 'UrbanMech', tier: 'present', note: 'canon 3025: 2% (UM-R60)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 2% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 2% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 2% (OTT-7J)' },
            { chassis: 'Panther', tier: 'present', note: 'canon 3025: 3% (PNT-9R)' },
            { chassis: 'Assassin', tier: 'present', note: 'canon 3025: 2% (ASN-21)' },
            { chassis: 'Cicada', tier: 'present', note: 'canon 3025: 2% (CDA-2A)' },
            { chassis: 'Hermes II', tier: 'rare', note: 'canon 3025: 1% (HER-4K — source prints \'Hermes III\' (sic))' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 2% (VL-2T)' },
            { chassis: 'Whitworth', tier: 'present', note: 'canon 3025: 3% (WTH-1, WTH-1S)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 3% (PXH-1, PXH-1K — source range \'31-31\' read as 31-32)' },
            { chassis: 'Hunchback', tier: 'present', note: 'canon 3025: 3% (HBK-4G, HBK-4H)' },
            { chassis: 'Trebuchet', tier: 'present', note: 'canon 3025: 3% (TBT-5N, TBT-7K)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 2% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 3% (SHD-2H, SHD-2K)' },
            { chassis: 'Scorpion', tier: 'present', note: 'canon 3025: 2% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 3% (WVR-6R, WVR-6K)' },
            { chassis: 'Dragon', tier: 'common', note: 'canon 3025: 4% (DRG-1N, DRG-1C)' },
            { chassis: 'Grand Dragon', tier: 'present', note: 'canon 3025: 2% (DRG-1G — kept separate from Dragon per source; may resolve to a Dragon variant in catalog)' },
            { chassis: 'Ostroc', tier: 'present', note: 'canon 3025: 3% (OSR-2C, OSR-3C)' },
            { chassis: 'Ostsol', tier: 'present', note: 'canon 3025: 3% (OTL-4D, OTL-4F)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 2% (RFL-3N)' },
            { chassis: 'Catapult', tier: 'rare', note: 'canon 3025: 1% (CPLT-K2)' },
            { chassis: 'Crusader', tier: 'rare', note: 'canon 3025: 1% (CRD-3K)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 2% (TDR-5S)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 3% (ARC-2R, ARC-2K); + ~0.15% Special (ARC-2W)' },
            { chassis: 'Grasshopper', tier: 'present', note: 'canon 3025: 2% (GHR-5H)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 2% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 2% (MAD-3R)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 2% (ON1-K)' },
            { chassis: 'Awesome', tier: 'present', note: 'canon 3025: 3% (AWS-8Q, AWS-6R (sic — likely AWS-8R))' },
            { chassis: 'Charger', tier: 'present', note: 'canon 3025: 2% (CGR-1A1)' },
            { chassis: 'Goliath', tier: 'present', note: 'canon 3025: 2% (GOL-1H)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 2% (BLR-1G)' },
            { chassis: 'Longbow', tier: 'present', note: 'canon 3025: 2% (LGB-OW); + ~0.21% Special (LGB-8C)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 2% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'present', note: 'canon 3025: 2% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'present', note: 'canon 3025: 2% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'present', note: 'canon 3025: 2% (AS7-D)' },
            { chassis: 'Firefly', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (FFL-4A)' },
            { chassis: 'Falcon', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (FLC-4N)' },
            { chassis: 'Flea', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.48% (FLE-4, FLE-15)' },
            { chassis: 'Hornet', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (HNT-151)' },
            { chassis: 'Wolfhound', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (WLF-1)' },
            { chassis: 'Chameleon', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (TBC-4B)' },
            { chassis: 'Hoplite', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (HP-4C)' },
            { chassis: 'Annihilator', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.15% (ANH-1A)' },
            { chassis: 'Shogun', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.15% (SHG-2E)' },
            { chassis: 'Imp', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.09% (IMP-2E)' },
            { chassis: 'Marauder II', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.09% (MAD-4A)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"DRACONIS COMBINE AVAILABILITY: 3025" d100 table — variants aggregated to chassis; Special (98-00 → rare-\'Mech subtable, 3%) folded in as rare entries at effective % (special % × subtable %)',
        ],
    },
    {
        faction: ['Federated Suns', 'House Davion'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'present', note: 'canon 3025: 3% (LCT-1V, LCT-1M)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 2% (STG-3R)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 3% (WSP-1A, WSP-1D); + ~0.24% Special (WSP-1A)' },
            { chassis: 'Javelin', tier: 'common', note: 'canon 3025: 4% (JVN-10N, JVN-10F)' },
            { chassis: 'Spider', tier: 'present', note: 'canon 3025: 3% (SDR-5V, SDR-5D)' },
            { chassis: 'UrbanMech', tier: 'rare', note: 'canon 3025: 1% (UM-R60)' },
            { chassis: 'Valkyrie', tier: 'common', note: 'canon 3025: 4% (VLK-QA, VLK-QF)' },
            { chassis: 'Firestarter', tier: 'rare', note: 'canon 3025: 1% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 2% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'rare', note: 'canon 3025: 1% (OTT-7J)' },
            { chassis: 'Assassin', tier: 'present', note: 'canon 3025: 3% (ASN-21, ASN-101)' },
            { chassis: 'Cicada', tier: 'rare', note: 'canon 3025: 1% (CDA-2A)' },
            { chassis: 'Clint', tier: 'rare', note: 'canon 3025: 1% (CLNT-2-3T)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 3% (VL-2T, VL-5T)' },
            { chassis: 'Whitworth', tier: 'rare', note: 'canon 3025: 1% (WTH-1)' },
            { chassis: 'Blackjack', tier: 'common', note: 'canon 3025: 4% (BJ-1, BJ-1DB, BJ-1DC)' },
            { chassis: 'Hatchetman', tier: 'present', note: 'canon 3025: 3% (HCT-3F, HCT-3NM)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 3% (PXH-1, PXH-1D)' },
            { chassis: 'Centurion', tier: 'present', note: 'canon 3025: 3% (CN9-A, CN9-AH)' },
            { chassis: 'Enforcer', tier: 'present', note: 'canon 3025: 3% (ENF-4R)' },
            { chassis: 'Hunchback', tier: 'rare', note: 'canon 3025: 1% (HBK-4G)' },
            { chassis: 'Trebuchet', tier: 'rare', note: 'canon 3025: 1% (TBT-5N — row mislabeled \'Hunchback\' in source)' },
            { chassis: 'Dervish', tier: 'rare', note: 'canon 3025: 1% (DV-6M)' },
            { chassis: 'Griffin', tier: 'rare', note: 'canon 3025: 1% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 3% (SHD-2H, SHD-2D)' },
            { chassis: 'Scorpion', tier: 'rare', note: 'canon 3025: 1% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'rare', note: 'canon 3025: 1% (WVR-6R)' },
            { chassis: 'Ostroc', tier: 'rare', note: 'canon 3025: 1% (OSR-2C)' },
            { chassis: 'Ostsol', tier: 'rare', note: 'canon 3025: 1% (OTL-4D)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 3% (RFL-3N, RFL-4D)' },
            { chassis: 'Catapult', tier: 'rare', note: 'canon 3025: 1% (CPLT-C1)' },
            { chassis: 'Crusader', tier: 'present', note: 'canon 3025: 3% (CRD-3R, CRD-3D)' },
            { chassis: 'JagerMech', tier: 'present', note: 'canon 3025: 3% (JM6-S, JM6-A)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 3% (TDR-5S, TDR-5SE)' },
            { chassis: 'Archer', tier: 'rare', note: 'canon 3025: 1% (ARC-2R); + ~0.15% Special (ARC-2W)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R, WHM-6D, WHM-6K)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 3% (MAD-3R, MAD-3D — 79-80 row mislabeled \'Warhammer\' in source)' },
            { chassis: 'Orion', tier: 'rare', note: 'canon 3025: 1% (ON1-K)' },
            { chassis: 'Awesome', tier: 'present', note: 'canon 3025: 3% (AWS-8Q, AWS-8V)' },
            { chassis: 'Charger', tier: 'rare', note: 'canon 3025: 1% (CGR-1A1)' },
            { chassis: 'Victor', tier: 'present', note: 'canon 3025: 2% (VTR-9B)' },
            { chassis: 'Zeus', tier: 'rare', note: 'canon 3025: 1% (ZEU-6S)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 3% (BLR-1G, BLR-1D)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 2% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'rare', note: 'canon 3025: 1% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'rare', note: 'canon 3025: 1% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'rare', note: 'canon 3025: 1% (AS7-D)' },
            { chassis: 'Firefly', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (FFL-4A)' },
            { chassis: 'Falcon', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (FLC-4N)' },
            { chassis: 'Flea', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.48% (FLE-4, FLE-15)' },
            { chassis: 'Hornet', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (HNT-151)' },
            { chassis: 'Wolfhound', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (WLF-1)' },
            { chassis: 'Chameleon', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (TBC-4B)' },
            { chassis: 'Hoplite', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (HP-4C)' },
            { chassis: 'Longbow', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.21% (LGB-8C)' },
            { chassis: 'Annihilator', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.15% (ANH-1A)' },
            { chassis: 'Shogun', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.15% (SHG-2E)' },
            { chassis: 'Imp', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.09% (IMP-2E)' },
            { chassis: 'Marauder II', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.09% (MAD-4A)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"FEDERATED SUNS AVAILABILITY: 3025" d100 table — variants aggregated to chassis; Special (98-00 → rare-\'Mech subtable, 3%) folded in as rare entries at effective % (special % × subtable %)',
        ],
    },
    {
        faction: ['Lyran Commonwealth', 'Lyran Alliance', 'House Steiner'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'present', note: 'canon 3025: 3% (LCT-1V, LCT-3V)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 2% (STG-3R)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 2% (WSP-1A); + ~0.4% Special (WSP-1A)' },
            { chassis: 'Commando', tier: 'common', note: 'canon 3025: 4% (COM-2D, COM-3A)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 3% (FS9-H, FS9-M)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 2% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 2% (OTT-7J)' },
            { chassis: 'Assassin', tier: 'present', note: 'canon 3025: 2% (ASN-21)' },
            { chassis: 'Cicada', tier: 'present', note: 'canon 3025: 2% (CDA-2A)' },
            { chassis: 'Clint', tier: 'present', note: 'canon 3025: 3% (CLNT-2-3T, CLNT-2-4T)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 2% (VL-2T)' },
            { chassis: 'Hatchetman', tier: 'present', note: 'canon 3025: 3% (HCT-3F, HCT-3NM)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 2% (PXH-1)' },
            { chassis: 'Centurion', tier: 'rare', note: 'canon 3025: 1% (CN9-AL)' },
            { chassis: 'Trebuchet', tier: 'present', note: 'canon 3025: 3% (TBT-5N, TBT-5S)' },
            { chassis: 'Dervish', tier: 'present', note: 'canon 3025: 2% (DV-6M)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 3% (GRF-1N, GRF-1S)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 2% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 2% (WVR-6R)' },
            { chassis: 'Quickdraw', tier: 'present', note: 'canon 3025: 3% (QKD-4G, QKD-4H)' },
            { chassis: 'Merlin', tier: 'rare', note: 'canon 3025: 1% (no model code printed in source; MLN-1A)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 2% (RFL-3N)' },
            { chassis: 'Catapult', tier: 'present', note: 'canon 3025: 3% (CPLT-C1, CPLT-A1)' },
            { chassis: 'Crusader', tier: 'present', note: 'canon 3025: 2% (CRD-3R)' },
            { chassis: 'JagerMech', tier: 'present', note: 'canon 3025: 2% (JM6-S)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 3% (TDR-5S, TDR-5SS)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 3% (ARC-2R, ARC-2S); + ~0.25% Special (ARC-2W)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 2% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 2% (MAD-3R)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 3% (ON1-K, ON1-V)' },
            { chassis: 'Goliath', tier: 'present', note: 'canon 3025: 2% (GOL-1H)' },
            { chassis: 'Victor', tier: 'present', note: 'canon 3025: 2% (VTR-9S, VTR-9A)' },
            { chassis: 'Zeus', tier: 'common', note: 'canon 3025: 5% (ZEU-6S, ZEU-6T)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 2% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F, STK-3H, STK-4N)' },
            { chassis: 'Cyclops', tier: 'present', note: 'canon 3025: 3% (CP-10-Z, CP-10-HQ)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E, BNC-3S)' },
            { chassis: 'Atlas', tier: 'present', note: 'canon 3025: 2% (AS7-D)' },
            { chassis: 'Firefly', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.4% (FFL-4A)' },
            { chassis: 'Falcon', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.4% (FLC-4N)' },
            { chassis: 'Flea', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.8% (FLE-4, FLE-15)' },
            { chassis: 'Hornet', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.4% (HNT-151)' },
            { chassis: 'Wolfhound', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.4% (WLF-1)' },
            { chassis: 'Chameleon', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.4% (TBC-4B)' },
            { chassis: 'Hoplite', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.4% (HP-4C)' },
            { chassis: 'Longbow', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.35% (LGB-8C)' },
            { chassis: 'Annihilator', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.25% (ANH-1A)' },
            { chassis: 'Shogun', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.25% (SHG-2E)' },
            { chassis: 'Imp', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.15% (IMP-2E)' },
            { chassis: 'Marauder II', tier: 'rare', note: 'canon 3025 Special (96-00 → subtable): ~0.15% (MAD-4A)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"LYRAN COMMONWEALTH AVAILABILITY: 3025" d100 table — variants aggregated to chassis; Special (96-00 → rare-\'Mech subtable, 5%) folded in as rare entries at effective % (special % × subtable %)',
        ],
    },
    {
        faction: ['Free Worlds League', 'House Marik'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'present', note: 'canon 3025: 2% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 3% (STG-3R, STG-3G)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 2% (WSP-1A); + ~0.24% Special (WSP-1A)' },
            { chassis: 'Spider', tier: 'present', note: 'canon 3025: 2% (SDR-5V)' },
            { chassis: 'UrbanMech', tier: 'present', note: 'canon 3025: 2% (UM-R60)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 2% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 2% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 2% (OTT-7J)' },
            { chassis: 'Assassin', tier: 'present', note: 'canon 3025: 2% (ASN-21)' },
            { chassis: 'Cicada', tier: 'present', note: 'canon 3025: 2% (CDA-2A)' },
            { chassis: 'Clint', tier: 'present', note: 'canon 3025: 2% (CLNT-2-3T)' },
            { chassis: 'Hermes II', tier: 'common', note: 'canon 3025: 5% (HER-2S, HER-2M)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 2% (VL-2T)' },
            { chassis: 'Blackjack', tier: 'present', note: 'canon 3025: 2% (BJ-1)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 2% (PXH-1)' },
            { chassis: 'Hunchback', tier: 'common', note: 'canon 3025: 4% (HBK-4G, HBK-4N, HBK-4SP)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N, TBT-5J, TBT-5T — stray \'52\' row read as 42)' },
            { chassis: 'Dervish', tier: 'present', note: 'canon 3025: 2% (DV-6M)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 2% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 2% (SHD-2H)' },
            { chassis: 'Scorpion', tier: 'present', note: 'canon 3025: 2% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 3% (WVR-6R, WVR-6M)' },
            { chassis: 'Ostroc', tier: 'rare', note: 'canon 3025: 1% (OSR-2M)' },
            { chassis: 'Quickdraw', tier: 'present', note: 'canon 3025: 3% (QKD-4G, QKD-5A)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 3% (RFL-3N, RFL-3C)' },
            { chassis: 'Crusader', tier: 'present', note: 'canon 3025: 2% (CRD-3R)' },
            { chassis: 'JagerMech', tier: 'present', note: 'canon 3025: 2% (JM6-S)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 2% (TDR-5S)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 2% (ARC-2R); + ~0.15% Special (ARC-2W)' },
            { chassis: 'Grasshopper', tier: 'present', note: 'canon 3025: 2% (GHR-5H)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 2% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 3% (MAD-3R, MAD-3M)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 2% (ON1-K)' },
            { chassis: 'Awesome', tier: 'present', note: 'canon 3025: 3% (AWS-8Q, AWS-8T)' },
            { chassis: 'Goliath', tier: 'present', note: 'canon 3025: 2% (GOL-1H)' },
            { chassis: 'Victor', tier: 'present', note: 'canon 3025: 3% (VTR-9B, VTR-9A1)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 2% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 2% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'present', note: 'canon 3025: 3% (CP-10-Z, CP-10-Q)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E, BNC-3M, BNC-3Q)' },
            { chassis: 'Atlas', tier: 'rare', note: 'canon 3025: 1% (AS7-D)' },
            { chassis: 'Firefly', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (FFL-4A)' },
            { chassis: 'Falcon', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (FLC-4N)' },
            { chassis: 'Flea', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.48% (FLE-4, FLE-15)' },
            { chassis: 'Hornet', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (HNT-151)' },
            { chassis: 'Wolfhound', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (WLF-1)' },
            { chassis: 'Chameleon', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (TBC-4B)' },
            { chassis: 'Hoplite', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.24% (HP-4C)' },
            { chassis: 'Longbow', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.21% (LGB-8C)' },
            { chassis: 'Annihilator', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.15% (ANH-1A)' },
            { chassis: 'Shogun', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.15% (SHG-2E)' },
            { chassis: 'Imp', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.09% (IMP-2E)' },
            { chassis: 'Marauder II', tier: 'rare', note: 'canon 3025 Special (98-00 → subtable): ~0.09% (MAD-4A)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"FREE WORLDS LEAGUE AVAILABILITY: 3025" d100 table — variants aggregated to chassis; Special (98-00 → rare-\'Mech subtable, 3%) folded in as rare entries at effective % (special % × subtable %)',
        ],
    },
    {
        faction: ['Capellan Confederation', 'House Liao'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'present', note: 'canon 3025: 3% (LCT-1V, LCT-1S)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 2% (STG-3R)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 3% (WSP-1A, WSP-1L); + ~0.32% Special (WSP-1W)' },
            { chassis: 'UrbanMech', tier: 'common', note: 'canon 3025: 5% (UM-R60, UM-R60L)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 2% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 3% (JR7-D, JR7-F)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 2% (OTT-7J)' },
            { chassis: 'Raven', tier: 'present', note: 'canon 3025: 3% (RVN-1X)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A, CDA-2B, CDA-3C)' },
            { chassis: 'Clint', tier: 'present', note: 'canon 3025: 3% (CLNT-2-3T, CLNT-1-2R)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 2% (VL-2T)' },
            { chassis: 'Blackjack', tier: 'present', note: 'canon 3025: 2% (BJ-1)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 2% (PXH-1)' },
            { chassis: 'Vindicator', tier: 'common', note: 'canon 3025: 6% (VND-1R, VND-1AA)' },
            { chassis: 'Hunchback', tier: 'common', note: 'canon 3025: 4% (HBK-4G, HBK-4S, HBK-4P)' },
            { chassis: 'Trebuchet', tier: 'present', note: 'canon 3025: 2% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 2% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 2% (SHD-2H)' },
            { chassis: 'Scorpion', tier: 'present', note: 'canon 3025: 2% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 2% (WVR-6R)' },
            { chassis: 'Ostroc', tier: 'present', note: 'canon 3025: 3% (OSR-2C, OSR-2L)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 2% (RFL-3N)' },
            { chassis: 'Catapult', tier: 'present', note: 'canon 3025: 3% (CPLT-C1, CPLT-C4)' },
            { chassis: 'Crusader', tier: 'rare', note: 'canon 3025: 1% (CRD-3L)' },
            { chassis: 'JagerMech', tier: 'present', note: 'canon 3025: 2% (JM6-S)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 2% (TDR-5S)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 2% (ARC-2R — row mislabeled \'Charger\' in source); + ~0.2% Special (ARC-2W)' },
            { chassis: 'Cataphract', tier: 'present', note: 'canon 3025: 3% (CTF-1X)' },
            { chassis: 'Grasshopper', tier: 'present', note: 'canon 3025: 2% (GHR-5H)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 3% (WHM-6R, WHM-6L)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 3% (MAD-3R, MAD-3L)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 3% (ON1-K, ON1-VA)' },
            { chassis: 'Charger', tier: 'common', note: 'canon 3025: 4% (CGR-1A1, CGR-1L, CGR-SB)' },
            { chassis: 'BattleMaster', tier: 'rare', note: 'canon 3025: 1% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 3% (STK-3F, STK-4P)' },
            { chassis: 'Cyclops', tier: 'rare', note: 'canon 3025: 1% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'rare', note: 'canon 3025: 1% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'rare', note: 'canon 3025: 1% (AS7-D)' },
            { chassis: 'Firefly', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.32% (FFL-4A)' },
            { chassis: 'Falcon', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.32% (FLC-4N)' },
            { chassis: 'Flea', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.64% (FLE-4, FLE-15)' },
            { chassis: 'Hornet', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.32% (HNT-151)' },
            { chassis: 'Wolfhound', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.32% (WLF-1)' },
            { chassis: 'Chameleon', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.32% (TBC-4B)' },
            { chassis: 'Hoplite', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.32% (HP-4C)' },
            { chassis: 'Longbow', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.28% (LGB-8C)' },
            { chassis: 'Annihilator', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.2% (ANH-1A)' },
            { chassis: 'Shogun', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.2% (SHG-2E)' },
            { chassis: 'Imp', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.12% (IMP-2E)' },
            { chassis: 'Marauder II', tier: 'rare', note: 'canon 3025 Special (97-00 → subtable): ~0.12% (MAD-4A)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"CAPELLAN CONFEDERATION AVAILABILITY: 3025" d100 table — variants aggregated to chassis; Special (97-00 → rare-\'Mech subtable, 4%) folded in as rare entries at effective % (special % × subtable %)',
        ],
    },
    {
        faction: ['Taurian Concordat'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'present', note: 'canon 3025: 3% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 3% (STG-3R — source range \'04-16\' read as 04-06)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 3% (WSP-1A)' },
            { chassis: 'Spider', tier: 'present', note: 'canon 3025: 3% (SDR-5V)' },
            { chassis: 'UrbanMech', tier: 'present', note: 'canon 3025: 3% (UM-R60)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 3% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 3% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 3% (OTT-7J)' },
            { chassis: 'Assassin', tier: 'present', note: 'canon 3025: 3% (ASN-21)' },
            { chassis: 'Cicada', tier: 'present', note: 'canon 3025: 3% (CDA-2A)' },
            { chassis: 'Clint', tier: 'present', note: 'canon 3025: 3% (CLNT-2-3T)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 3% (VL-2T)' },
            { chassis: 'Blackjack', tier: 'present', note: 'canon 3025: 3% (BJ-1)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 3% (PXH-1)' },
            { chassis: 'Hunchback', tier: 'present', note: 'canon 3025: 3% (HBK-4G)' },
            { chassis: 'Trebuchet', tier: 'present', note: 'canon 3025: 3% (TBT-5N)' },
            { chassis: 'Dervish', tier: 'present', note: 'canon 3025: 3% (DV-6M)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 3% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 3% (SHD-2H)' },
            { chassis: 'Scorpion', tier: 'present', note: 'canon 3025: 3% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 3% (WVR-6R)' },
            { chassis: 'Ostroc', tier: 'present', note: 'canon 3025: 3% (OSR-2C)' },
            { chassis: 'Ostsol', tier: 'present', note: 'canon 3025: 3% (OTL-4D)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 3% (RFL-3N)' },
            { chassis: 'Catapult', tier: 'present', note: 'canon 3025: 3% (CPLT-C1)' },
            { chassis: 'Crusader', tier: 'present', note: 'canon 3025: 3% (CRD-3R)' },
            { chassis: 'JagerMech', tier: 'present', note: 'canon 3025: 3% (JM6-S)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 3% (TDR-5S)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 3% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 3% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 2% (MAD-3R)' },
            { chassis: 'Orion', tier: 'rare', note: 'canon 3025: 1% (ON1-K)' },
            { chassis: 'Awesome', tier: 'rare', note: 'canon 3025: 1% (AWS-8Q)' },
            { chassis: 'Charger', tier: 'rare', note: 'canon 3025: 1% (CGR-1A1)' },
            { chassis: 'BattleMaster', tier: 'rare', note: 'canon 3025: 1% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'rare', note: 'canon 3025: 1% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'rare', note: 'canon 3025: 1% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'rare', note: 'canon 3025: 1% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'rare', note: 'canon 3025: 1% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"TAURIAN CONCORDAT AVAILABILITY: 3025" d100 table — variants aggregated to chassis; near-flat: 3% across 30 chassis with a thin 1-2% assault tail — that IS canon; binned honestly per header rule',
        ],
    },
    {
        faction: ['Magistracy of Canopus'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 4% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 4% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 4% (WSP-1A)' },
            { chassis: 'UrbanMech', tier: 'present', note: 'canon 3025: 3% (UM-R60)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 3% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 3% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 3% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'present', note: 'canon 3025: 3% (CDA-2A)' },
            { chassis: 'Clint', tier: 'present', note: 'canon 3025: 3% (CLNT-2-3T)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 3% (VL-2T)' },
            { chassis: 'Blackjack', tier: 'present', note: 'canon 3025: 3% (BJ-1)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 3% (PXH-1)' },
            { chassis: 'Hunchback', tier: 'present', note: 'canon 3025: 3% (HBK-4G)' },
            { chassis: 'Trebuchet', tier: 'present', note: 'canon 3025: 3% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 3% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 3% (SHD-2H)' },
            { chassis: 'Scorpion', tier: 'present', note: 'canon 3025: 3% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 3% (WVR-6R)' },
            { chassis: 'Ostroc', tier: 'present', note: 'canon 3025: 3% (OSR-2C)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 3% (RFL-3N)' },
            { chassis: 'Catapult', tier: 'present', note: 'canon 3025: 3% (CPLT-C1)' },
            { chassis: 'JagerMech', tier: 'present', note: 'canon 3025: 3% (JM6-S)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 3% (TDR-5S)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 3% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 3% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 3% (MAD-3R)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 3% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 3% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 3% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'present', note: 'canon 3025: 3% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'present', note: 'canon 3025: 3% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"MAGISTRACY OF CANOPUS AVAILABILITY: 3025" d100 table — variants aggregated to chassis; near-flat: 3-4% rows throughout — that IS canon; binned honestly per header rule',
        ],
    },
    {
        faction: ['Outworlds Alliance'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 4% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'present', note: 'canon 3025: 3% (STG-3R)' },
            { chassis: 'Wasp', tier: 'present', note: 'canon 3025: 3% (WSP-1A)' },
            { chassis: 'UrbanMech', tier: 'present', note: 'canon 3025: 3% (UM-R60)' },
            { chassis: 'Firestarter', tier: 'present', note: 'canon 3025: 3% (FS9-H)' },
            { chassis: 'Jenner', tier: 'present', note: 'canon 3025: 3% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'present', note: 'canon 3025: 3% (OTT-7J)' },
            { chassis: 'Assassin', tier: 'present', note: 'canon 3025: 3% (ASN-21)' },
            { chassis: 'Cicada', tier: 'present', note: 'canon 3025: 3% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'present', note: 'canon 3025: 3% (VL-2T)' },
            { chassis: 'Whitworth', tier: 'present', note: 'canon 3025: 3% (WTH-1)' },
            { chassis: 'Phoenix Hawk', tier: 'present', note: 'canon 3025: 3% (PXH-1)' },
            { chassis: 'Hunchback', tier: 'present', note: 'canon 3025: 3% (HBK-4G)' },
            { chassis: 'Trebuchet', tier: 'present', note: 'canon 3025: 3% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'present', note: 'canon 3025: 3% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'present', note: 'canon 3025: 3% (SHD-2H)' },
            { chassis: 'Scorpion', tier: 'present', note: 'canon 3025: 3% (SCP-1N)' },
            { chassis: 'Wolverine', tier: 'present', note: 'canon 3025: 3% (WVR-6R)' },
            { chassis: 'Ostroc', tier: 'present', note: 'canon 3025: 3% (OSR-2C)' },
            { chassis: 'Ostsol', tier: 'present', note: 'canon 3025: 3% (OTL-4D)' },
            { chassis: 'Rifleman', tier: 'present', note: 'canon 3025: 3% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'present', note: 'canon 3025: 3% (TDR-5S)' },
            { chassis: 'Archer', tier: 'present', note: 'canon 3025: 3% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'present', note: 'canon 3025: 3% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 3% (MAD-3R)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 3% (ON1-K)' },
            { chassis: 'Awesome', tier: 'present', note: 'canon 3025: 3% (AWS-8Q)' },
            { chassis: 'Charger', tier: 'present', note: 'canon 3025: 3% (CGR-1A1)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 3% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 3% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'present', note: 'canon 3025: 3% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'present', note: 'canon 3025: 3% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'present', note: 'canon 3025: 3% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"OUTWORLDS ALLIANCE AVAILABILITY: 3025" d100 table — variants aggregated to chassis; near-flat: 3-4% rows throughout — that IS canon; binned honestly per header rule (BLR-1GT in source normalized to BLR-1G)',
        ],
    },
    {
        faction: ['Pirates', 'Bandits', 'Oberon Confederation', 'Tortuga Dominions', 'Greater Valkyrate'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 4% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 4% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 4% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 4% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Assassin', tier: 'common', note: 'canon 3025: 4% (ASN-21)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Ostsol', tier: 'common', note: 'canon 3025: 4% (OTL-4D)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'present', note: 'canon 3025: 3% (MAD-3R)' },
            { chassis: 'Orion', tier: 'present', note: 'canon 3025: 3% (ON1-K)' },
            { chassis: 'Goliath', tier: 'present', note: 'canon 3025: 3% (GOL-1H)' },
            { chassis: 'BattleMaster', tier: 'present', note: 'canon 3025: 3% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'present', note: 'canon 3025: 3% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'present', note: 'canon 3025: 3% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'present', note: 'canon 3025: 3% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'present', note: 'canon 3025: 3% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"BANDIT KINGDOMS AVAILABILITY: 3025" d100 table — variants aggregated to chassis; flat: 4% light/medium rows, 3% heavy/assault rows — that IS canon (loot is loot); binned honestly per header rule',
        ],
    },
    {
        faction: ['Illyrian Palatinate'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 5% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 5% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 5% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 5% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'common', note: 'canon 3025: 4% (MAD-3R)' },
            { chassis: 'Orion', tier: 'common', note: 'canon 3025: 4% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'common', note: 'canon 3025: 4% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'common', note: 'canon 3025: 4% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'common', note: 'canon 3025: 4% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"ILLYRIAN PALATINATE AVAILABILITY: 3025" d100 table — variants aggregated to chassis; FLAT: the generic 24-chassis periphery list (4-5% rows ⇒ everything common-tier) — that IS canon; binned honestly per header rule',
        ],
    },
    {
        faction: ['Lothian League'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 5% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 5% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 5% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 5% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'common', note: 'canon 3025: 4% (MAD-3R)' },
            { chassis: 'Orion', tier: 'common', note: 'canon 3025: 4% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'common', note: 'canon 3025: 4% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'common', note: 'canon 3025: 4% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'common', note: 'canon 3025: 4% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"LOTHIAN LEAGUE AVAILABILITY: 3025" d100 table — variants aggregated to chassis; FLAT: the generic 24-chassis periphery list (4-5% rows ⇒ everything common-tier) — that IS canon; binned honestly per header rule (case slips in source normalized)',
        ],
    },
    {
        faction: ['Elysian Fields'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 5% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 5% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 5% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 5% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'common', note: 'canon 3025: 4% (MAD-3R)' },
            { chassis: 'Orion', tier: 'common', note: 'canon 3025: 4% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'common', note: 'canon 3025: 4% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'common', note: 'canon 3025: 4% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'common', note: 'canon 3025: 4% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"ELYSIAN FIELDS AVAILABILITY: 3025" d100 table — variants aggregated to chassis; FLAT: the generic 24-chassis periphery list (4-5% rows ⇒ everything common-tier) — that IS canon; binned honestly per header rule (BLR-1TG/AT7-D typos in source normalized to BLR-1G/AS7-D)',
        ],
    },
    {
        faction: ['Port Krin', 'Antallos'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 5% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 5% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 5% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 5% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'common', note: 'canon 3025: 4% (MAD-3R)' },
            { chassis: 'Orion', tier: 'common', note: 'canon 3025: 4% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'common', note: 'canon 3025: 4% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'common', note: 'canon 3025: 4% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'common', note: 'canon 3025: 4% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"PORT KRIN AVAILABILITY: 3025" d100 table — variants aggregated to chassis; FLAT: the generic 24-chassis periphery list (4-5% rows ⇒ everything common-tier) — that IS canon; binned honestly per header rule (case slips in source normalized)',
        ],
    },
    {
        faction: ['Barony of Strang'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 5% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 5% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 5% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 5% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'common', note: 'canon 3025: 4% (MAD-3R)' },
            { chassis: 'Orion', tier: 'common', note: 'canon 3025: 4% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'common', note: 'canon 3025: 4% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'common', note: 'canon 3025: 4% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'common', note: 'canon 3025: 4% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"BARONY OF STRANG AVAILABILITY: 3025" d100 table — variants aggregated to chassis; FLAT: the generic 24-chassis periphery list (4-5% rows ⇒ everything common-tier) — that IS canon; binned honestly per header rule (BLR-1GT typo in source normalized to BLR-1G)',
        ],
    },
    {
        faction: ['Mica Majority'], yearFrom: 2867, yearTo: 3049,
        entries: [
            { chassis: 'Locust', tier: 'common', note: 'canon 3025: 5% (LCT-1V)' },
            { chassis: 'Stinger', tier: 'common', note: 'canon 3025: 5% (STG-3R)' },
            { chassis: 'Wasp', tier: 'common', note: 'canon 3025: 5% (WSP-1A)' },
            { chassis: 'Firestarter', tier: 'common', note: 'canon 3025: 5% (FS9-H)' },
            { chassis: 'Jenner', tier: 'common', note: 'canon 3025: 4% (JR7-D)' },
            { chassis: 'Ostscout', tier: 'common', note: 'canon 3025: 4% (OTT-7J)' },
            { chassis: 'Cicada', tier: 'common', note: 'canon 3025: 4% (CDA-2A)' },
            { chassis: 'Vulcan', tier: 'common', note: 'canon 3025: 4% (VL-2T)' },
            { chassis: 'Phoenix Hawk', tier: 'common', note: 'canon 3025: 4% (PXH-1)' },
            { chassis: 'Trebuchet', tier: 'common', note: 'canon 3025: 4% (TBT-5N)' },
            { chassis: 'Griffin', tier: 'common', note: 'canon 3025: 4% (GRF-1N)' },
            { chassis: 'Shadow Hawk', tier: 'common', note: 'canon 3025: 4% (SHD-2H)' },
            { chassis: 'Wolverine', tier: 'common', note: 'canon 3025: 4% (WVR-6R)' },
            { chassis: 'Rifleman', tier: 'common', note: 'canon 3025: 4% (RFL-3N)' },
            { chassis: 'Thunderbolt', tier: 'common', note: 'canon 3025: 4% (TDR-5S)' },
            { chassis: 'Archer', tier: 'common', note: 'canon 3025: 4% (ARC-2R)' },
            { chassis: 'Warhammer', tier: 'common', note: 'canon 3025: 4% (WHM-6R)' },
            { chassis: 'Marauder', tier: 'common', note: 'canon 3025: 4% (MAD-3R)' },
            { chassis: 'Orion', tier: 'common', note: 'canon 3025: 4% (ON1-K)' },
            { chassis: 'BattleMaster', tier: 'common', note: 'canon 3025: 4% (BLR-1G)' },
            { chassis: 'Stalker', tier: 'common', note: 'canon 3025: 4% (STK-3F)' },
            { chassis: 'Cyclops', tier: 'common', note: 'canon 3025: 4% (CP-10-Z)' },
            { chassis: 'Banshee', tier: 'common', note: 'canon 3025: 4% (BNC-3E)' },
            { chassis: 'Atlas', tier: 'common', note: 'canon 3025: 4% (AS7-D)' },
        ],
        sources: [
            'https://www.sarna.net/files/data/random_unit_tables/ — random_mech_table_3025.txt (harvested 2026-06-11, see reference/sarna/HARVEST.md; archive reference/sarna/random_unit_tables/random_mech_table_3025.zip)',
            '"MICA MAJORITY AVAILABILITY: 3025" d100 table — variants aggregated to chassis; FLAT: the generic 24-chassis periphery list (4-5% rows ⇒ everything common-tier) — that IS canon; binned honestly per header rule (OTT-7S / bare RFL- model slips in source normalized to OTT-7J / RFL-3N)',
        ],
    },
];
